spring:
  application:
    name: book

  cloud:
    config:
      uri: http://localhost:8081

    bus:
      enabled: false

    discovery:
      enabled: false
server:
  port: 8081

management:
  security:
    enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

api:
  author:
    uri: http://localhost:8080

logging:
  level:
    org:
      springframework:
        web: INFO
  file: C:/temp/log/bookApi.log