spring.application.name=book

spring.cloud.config.uri=http://localhost:8081
server.port=8081
management.security.enabled=false
spring.cloud.bus.enabled=false

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

api.authorUri=http://localhost:8080